NAME_SYSTEM_MEASURE = "system_measures"
NUMBER_SYSTEM_MEASURE = 0
NAME_STAVE_MEASURE = "stave_measures"
NUMBER_STAVE_MEASURE = 1
NAME_STAVES = "staves"
NUMBER_STAVES = 2
NAME_SYSTEMS = "systems"
NUMBER_SYSTEMS = 3
NAME_GRAND_STAFF = "grand_staff"
NUMBER_GRAND_STAFF = 4

CLASS_NAMES = [
    NAME_SYSTEM_MEASURE,
    NAME_STAVE_MEASURE,
    NAME_STAVES,
    NAME_SYSTEMS,
    NAME_GRAND_STAFF
]
